# Generated by Django 4.2.1 on 2023-05-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('url', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('subscription_level', models.IntegerField(choices=[(0, 'Free'), (1, 'Iron'), (2, 'Bronze'), (3, 'Silver'), (4, 'Gold'), (5, 'Diamond')], default=0)),
            ],
            options={
                'verbose_name': 'Dashboard Menu',
                'verbose_name_plural': 'Dashboard Menus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProfileMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('url', models.CharField(max_length=50, unique=True)),
                ('subscription_level', models.IntegerField(choices=[(0, 'Free'), (1, 'Iron'), (2, 'Bronze'), (3, 'Silver'), (4, 'Gold'), (5, 'Diamond')], default=0)),
            ],
            options={
                'verbose_name': 'Profile Menu',
                'verbose_name_plural': 'Profile Menus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('url', models.CharField(max_length=50, unique=True)),
                ('subscription_level', models.IntegerField(choices=[(0, 'Free'), (1, 'Iron'), (2, 'Bronze'), (3, 'Silver'), (4, 'Gold'), (5, 'Diamond')], default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardmenu')),
            ],
            options={
                'verbose_name': 'Dashboard Submenu',
                'verbose_name_plural': 'Dashboard Submenus',
                'ordering': ['order'],
            },
        ),
    ]
