# Generated by Django 4.2.1 on 2023-05-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userconfig_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfig',
            options={'ordering': ['id'], 'verbose_name': 'User Configuration', 'verbose_name_plural': 'User Configuration'},
        ),
    ]
